# Site settings
title: Matthew's Cooking Page
email: 
description: > # this means to ignore newlines until "baseurl:"
  Matthew's Cooking Page
baseurl: "/cooking/" # the subpath of your site, e.g. /blog/
url: "https://matthewja.com" # the base hostname & protocol for your site
twitter_username: indecisivematt
github_username: matthewja

collections:
  recipes:
    output: true
    layout: recipe
defaults:
  - scope:
      path: ""
      type: "recipe"
    values:
      layout: "recipe"
